name               = "tg-bot"
main               = "build/worker/shim.mjs"
compatibility_date = "2026-03-06"

[build]
command = "/home/own/.cargo/bin/worker-build --release"

[vars]
ADMIN_TG = "AdmDeva"
PRELAND_URL = "https://comedownl.shop"
TG_BOT = "HDevaBot"
